The navigation bar
Chrysalis-Papilio/Soen-490-Papilio pull request #11
Opened 2022-10-22 18:52 UTC by BunnyPrince

Need the nav bar to start creating the activity page

2022-10-22 19:16 UTC, AC159 commented on app/build.gradle
> +    //implementation 'androidx.test:monitor:1.5.0'
Remove this line please

2022-10-22 19:17 UTC, AC159 commented on app/src/androidTest/java/com/soen490chrysalis/papilio/LoginActivityUITest.kt
> +
Same thing here

2022-10-22 19:19 UTC, AC159 commented on app/src/main/java/com/soen490chrysalis/papilio/view/InitialActivity.kt
> +import android.view.View
Is this import needed?

2022-10-22 19:19 UTC, AC159 commented on app/src/main/java/com/soen490chrysalis/papilio/view/InitialActivity.kt
> +
Remove these lines

2022-10-22 19:23 UTC, AC159 requested changes
See comments

2022-11-01 15:38 UTC, AC159 commented
Is there any progress on this side?

2022-11-01 17:33 UTC, DrakeHunterK7 commented
> Is there any progress on this side?

Will be done by today end or tomorrow latest

2022-11-07 01:35 UTC, closed without merging